from Tablero import *

a = Tablero()
a.ImprimirTablero()
a.GenericMove((1, (7, 1), 0, (5, 2), 0, 0, '\x1b[97m'))
a.ImprimirTablero()
a.GenericMove((1, (0, 1), 0, (2, 2), 0, 0, '\x1b[30m'))
a.ImprimirTablero()
a.GenericMove((2, (6, 4), 0, (5, 4), (4, 4), 0, '\x1b[97m'))
a.ImprimirTablero()
a.GenericMove((2, (2, 2), 0, (3, 4), (4, 1), 0, '\x1b[30m'))
a.ImprimirTablero()
a.Move([7,3],[3,7],BColors.WHITE)
a.ImprimirTablero()
a.Move([3,7],[1,5],BColors.WHITE)
a.ImprimirTablero()
a.Move([1,4],[2,4],BColors.BLACK)
a.ImprimirTablero()
zzz = a.GetMoves('B')
print(zzz)
a.Move([7,5],[5,3],BColors.WHITE)
a.Split([5,3],[6,4],[7,5], BColors.WHITE)
a.Move([6,6],[5,6],BColors.WHITE)
a.Move([7,5],[5,7],BColors.WHITE)
a.ImprimirTablero()
a.Move([7,4],[7,5],BColors.WHITE)
a.Move([5,7],[1,3],BColors.WHITE)
a.ImprimirTablero()
a.ImprimirCircuito()
print(a.piezas[20].posiciones)
'''
a = Tablero()
a.Move([0,3],[2,5], BColors.BLACK)
a.ImprimirTablero()
zzz = a.GetMoves('B')
print(zzz)
print(len(zzz) == len(set(zzz)))
print(len(zzz))
if (1, (1,0), (2,1),0) in zzz: print("GG")
if (2, (1,0), (2,1), (2, 0), 0) in zzz: print("GG")
a.Split([1,0],[2,0], [2, 2], BColors.BLACK)
a.ImprimirTablero()
#a.ImprimirCircuito()
a.Move([1,0],[3,0],BColors.BLACK)
a.Move([6,1],[4,1],BColors.WHITE)
#a.ImprimirTablero()
#a.Move([3,0],[4,0],BColors.BLACK)
#a.Move([4,0],[5,1],BColors.BLACK)
a.Move([4,1],[3,0],BColors.WHITE)
a.Move([7,1],[5,2],BColors.WHITE)
a.Move([7,2],[5,4],BColors.WHITE)
a.Move([7,2],[5,0],BColors.WHITE)
a.Move([3,0],[2,0],BColors.WHITE)
a.Move([2,0],[1,0],BColors.WHITE)
a.Move([1,0],[0,1],BColors.WHITE)
a.ImprimirTablero()
a.ImprimirCircuito()
a.Move([0,1],[0,2],BColors.WHITE)
a.Split([5,0],[4,1], [3, 2], BColors.WHITE)


a.ImprimirTablero()
a.ImprimirCircuito()
a.ImprimirProbabilidades()
a.Move([3,2],[1,4], BColors.WHITE)
a.ImprimirTablero()
#a.ImprimirProbabilidades()
#if a.tablero[1, 4] == "B": break
a.Split([6,3],[5,3],[4,3], BColors.WHITE)
a.Split([6,4],[5,4],[4,4], BColors.WHITE)
a.ImprimirTablero()
a.Split([7,5],[4,2], [3,1], BColors.WHITE)
#a.Move([7,5],[3,1], BColors.WHITE)
a.ImprimirTablero()
a.Move([3,1],[1,3], BColors.WHITE)
a.ImprimirTablero()
a.Split([7,4],[6,4],[6,3], BColors.WHITE)
a.Move([6,0], [4,0], BColors.WHITE)
a.Split([7,0], [5,0], [7,2], BColors.WHITE)
a.Split([7,3],[7,1],[5,5], BColors.WHITE)
a.ImprimirTablero()
#a.ImprimirProbabilidades()
a.Move([5,5],[1,5],BColors.WHITE)
a.ImprimirTablero()
a.Split([6,7], [5,7], [4,7], BColors.WHITE)
a.ImprimirTablero()
a.Move([7,7], [3,7], BColors.WHITE)
a.ImprimirTablero()
a.Move([3,7], [1,7], BColors.WHITE)
a.ImprimirTablero()
zzz = a.GetMoves('B')
print(zzz)
print(len(zzz) == len(set(zzz)))
print(len(zzz))
a.Move([0,0], [1,0], BColors.BLACK)
a.ImprimirTablero()
#a.ImprimirCircuito()
'''